onedayjob_api:
    resource: "@OneDayJobApiBundle/Resources/config/routing.yml"
    prefix: /api/{_locale}
    requirements:
        _locale: ru|en|de

onedayjob_frontend:
    resource: "@OneDayJobFrontendBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ru|en|de|pp

onedayjob_controlpanel:
    resource: "@OneDayJobControlpanelBundle/Controller/"
    type:     annotation

onedayjob_redirect_locale:
    pattern: /
    defaults: { _controller: OneDayJobFrontendBundle:Default:redirectLocale }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    requirements:
        _locale: ru|en|de|pp

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
