security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_EMPLOYEE:    ROLE_USER ROLE_EMPLOYEE
        ROLE_EMPLOYER:    ROLE_USER ROLE_EMPLOYER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                csrf_provider: form.csrf_provider
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                path: fos_user_security_logout
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/controlpanel/, role: ROLE_ADMIN }